// IHwShareCallback.idl

// Declare any non-default types here with sequenceable or interface statements

interface com.huawei.hwshare.third.IHwShareCallback {
    [oneway] void notifyState([in] int state);
}
